<?php

namespace ContactBundle\Repository;

/**
 * ContactGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName(){
        $em = $this->getEntityManager();
        $groups = $em->createQuery(
            'SELECT g FROM ContactBundle:ContactGroup g ORDER BY g.name ASC'
        )->getResult();
        return $groups;
    }
}
